### ISSUE TITLE
Is there chapter 1 only?

### ISSUE THREAD

**Issue by ZedZipDev** [PacktPublishing/Actionable-Insights-with-Amazon-QuickSight#1]
In the comment
"With the following software and hardware list you can run all code files present in the book (Chapter 1-10)."
but  the code has chapter_1 folder only. 
Is it ok? Where code for the rest chapters?

**Comment by samatase** [comment]
Thanks for reading my book, I hope you find it helpful, and thanks for giving me valuable feedback. Following your comment,  I have added the rest of the CLI commands, policy documents and python code for the remaining chapters. The chapters 2 and 4 have no code, only on screen instructions that you follow along reading the book.

**Comment by samatase** [comment]
Hi 
Thanks for your comment.
Chapter 1 instructions will help you set up your environment! 
The following chapters, have a mix of actions that are completed via the UI or the CLI.
I need to upload the rest of the cli commands in GitHub. In the meantime once you set up your environment, you can just go through the book instructions
Manos 

>
